### ISSUE TITLE
Checking up

### ISSUE THREAD

**Issue by Milimeter** [Ronak99/Flutter-Auth-Providers#1]
Hello CS GUY. How are you doing?
I was an active follower when you were creating the skype clone.
You just left and went AWOL brother for 2 years. 
I hope you are alright :)
I am a fan of yours. 
Well, I just remembered this evening about the guy that thought me a lot about logic-based coding.
Please just post any random video on your YouTube account because I believe there are others like me who miss you.
Please I'd love to reach out to you. Can you please message me at razaqolad300@gmail.com

**Comment by Ronak99** [comment]
Hello Oladapo Abdulrazaq,
Thank you for this amazing message.
I have been away for way too long, I am trying to get back on track with youtube, and was in the middle of editing a video when I received this message.
Will be posting videos soon.
